# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4bd750a861f9034b257da4182f8a209a96ffc244ec2d265166efb3e74c9b83cf771e401054d6eaa1b3096bb2ce695cd50719ff2cab50a32da536963af1645188

test:
  secret_key_base: e23cc4a9d25d8c217690f591052f90282210575c41f947a2455a134cfca59a5519c9f2f238138b61cc10c8ae2fe65b014ac8afa48e4c7f798fec6189c75f7613

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
